WebProject/WebProject/Controllers/ChampionRotationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProject.Data;
using WebProject.Models;

namespace WebProject.Controllers
{
    public class ChampionRotationsController : Controller
    {
        private readonly WebProjectContext _context;

        public ChampionRotationsController(WebProjectContext context)
        {
            _context = context;
        }

        // GET: ChampionRotations
        public async Task<IActionResult> Index()
        {
            var webProjectContext = _context.ChampionRotation.Include(c => c.Champion);
            return View(await webProjectContext.ToListAsync());
        }

        // GET: ChampionRotations/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championRotation = await _context.ChampionRotation
                .Include(c => c.Champion)
                .FirstOrDefaultAsync(m => m.ChampionId == id);
            if (championRotation == null)
            {
                return NotFound();
            }

            return View(championRotation);
        }

        // GET: ChampionRotations/Create
        public IActionResult Create()
        {
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id");
            return View();
        }

        // POST: ChampionRotations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChampionId")] ChampionRotation championRotation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(championRotation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id", championRotation.ChampionId);
            return View(championRotation);
        }

        // GET: ChampionRotations/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championRotation = await _context.ChampionRotation.FindAsync(id);
            if (championRotation == null)
            {
                return NotFound();
            }
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id", championRotation.ChampionId);
            return View(championRotation);
        }

        // POST: ChampionRotations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ChampionId")] ChampionRotation championRotation)
        {
            if (id != championRotation.ChampionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(championRotation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChampionRotationExists(championRotation.ChampionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id", championRotation.ChampionId);
            return View(championRotation);
        }

        // GET: ChampionRotations/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championRotation = await _context.ChampionRotation
                .Include(c => c.Champion)
                .FirstOrDefaultAsync(m => m.ChampionId == id);
            if (championRotation == null)
            {
                return NotFound();
            }

            return View(championRotation);
        }

        // POST: ChampionRotations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var championRotation = await _context.ChampionRotation.FindAsync(id);
            _context.ChampionRotation.Remove(championRotation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChampionRotationExists(string id)
        {
            return _context.ChampionRotation.Any(e => e.ChampionId == id);
        }
    }
}

WebProject/WebProject/Controllers/SummonerChampionMasteriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProject.Data;
using WebProject.Models;

namespace WebProject.Controllers
{
    public class SummonerChampionMasteriesController : Controller
    {
        private readonly WebProjectContext _context;

        public SummonerChampionMasteriesController(WebProjectContext context)
        {
            _context = context;
        }

        // GET: SummonerChampionMasteries
        public async Task<IActionResult> Index()
        {
            var webProjectContext = _context.SummonerChampionMastery.Include(s => s.Champion).Include(s => s.Summoner);
            return View(await webProjectContext.ToListAsync());
        }

        // GET: SummonerChampionMasteries/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summonerChampionMastery = await _context.SummonerChampionMastery
                .Include(s => s.Champion)
                .Include(s => s.Summoner)
                .FirstOrDefaultAsync(m => m.ChampionId == id);
            if (summonerChampionMastery == null)
            {
                return NotFound();
            }

            return View(summonerChampionMastery);
        }

        // GET: SummonerChampionMasteries/Create
        public IActionResult Create()
        {
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id");
            ViewData["SummonerId"] = new SelectList(_context.Summoner, "Id", "Id");
            return View();
        }

        // POST: SummonerChampionMasteries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChampionId,ChampionLevel,ChampionPoint,LastPlayTime,ChestGranted,TokensEarned,SummonerId")] SummonerChampionMastery summonerChampionMastery)
        {
            if (ModelState.IsValid)
            {
                _context.Add(summonerChampionMastery);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id", summonerChampionMastery.ChampionId);
            ViewData["SummonerId"] = new SelectList(_context.Summoner, "Id", "Id", summonerChampionMastery.SummonerId);
            return View(summonerChampionMastery);
        }

        // GET: SummonerChampionMasteries/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summonerChampionMastery = await _context.SummonerChampionMastery.FindAsync(id);
            if (summonerChampionMastery == null)
            {
                return NotFound();
            }
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id", summonerChampionMastery.ChampionId);
            ViewData["SummonerId"] = new SelectList(_context.Summoner, "Id", "Id", summonerChampionMastery.SummonerId);
            return View(summonerChampionMastery);
        }

        // POST: SummonerChampionMasteries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ChampionId,ChampionLevel,ChampionPoint,LastPlayTime,ChestGranted,TokensEarned,SummonerId")] SummonerChampionMastery summonerChampionMastery)
        {
            if (id != summonerChampionMastery.ChampionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(summonerChampionMastery);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SummonerChampionMasteryExists(summonerChampionMastery.ChampionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChampionId"] = new SelectList(_context.Champion, "Id", "Id", summonerChampionMastery.ChampionId);
            ViewData["SummonerId"] = new SelectList(_context.Summoner, "Id", "Id", summonerChampionMastery.SummonerId);
            return View(summonerChampionMastery);
        }

        // GET: SummonerChampionMasteries/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summonerChampionMastery = await _context.SummonerChampionMastery
                .Include(s => s.Champion)
                .Include(s => s.Summoner)
                .FirstOrDefaultAsync(m => m.ChampionId == id);
            if (summonerChampionMastery == null)
            {
                return NotFound();
            }

            return View(summonerChampionMastery);
        }

        // POST: SummonerChampionMasteries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var summonerChampionMastery = await _context.SummonerChampionMastery.FindAsync(id);
            _context.SummonerChampionMastery.Remove(summonerChampionMastery);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SummonerChampionMasteryExists(string id)
        {
            return _context.SummonerChampionMastery.Any(e => e.ChampionId == id);
        }
    }
}

WebProject/WebProject/Controllers/SummonersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProject.Data;
using WebProject.Models;

namespace WebProject.Controllers
{
    public class SummonersController : Controller
    {
        private readonly WebProjectContext _context;

        public SummonersController(WebProjectContext context)
        {
            _context = context;
        }

        // GET: Summoners
        public async Task<IActionResult> Index()
        {
            return View(await _context.Summoner.ToListAsync());
        }

        // GET: Summoners/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summoner = await _context.Summoner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (summoner == null)
            {
                return NotFound();
            }

            return View(summoner);
        }

        // GET: Summoners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Summoners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AccountId,PuuId,Name,ProfileIconId,RevisionDate,SummonerLevel")] Summoner summoner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(summoner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(summoner);
        }

        // GET: Summoners/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summoner = await _context.Summoner.FindAsync(id);
            if (summoner == null)
            {
                return NotFound();
            }
            return View(summoner);
        }

        // POST: Summoners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,AccountId,PuuId,Name,ProfileIconId,RevisionDate,SummonerLevel")] Summoner summoner)
        {
            if (id != summoner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(summoner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SummonerExists(summoner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(summoner);
        }

        // GET: Summoners/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summoner = await _context.Summoner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (summoner == null)
            {
                return NotFound();
            }

            return View(summoner);
        }

        // POST: Summoners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var summoner = await _context.Summoner.FindAsync(id);
            _context.Summoner.Remove(summoner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SummonerExists(string id)
        {
            return _context.Summoner.Any(e => e.Id == id);
        }
    }
}

WebProject/WebProject/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @using Microsoft.AspNetCore.Identity
    @inject SignInManager<IdentityUser> SignInManager
    @inject UserManager<IdentityUser> UserManager
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel</title>
    <link rel="stylesheet" href="~/css/AdminPanel.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <asp:ContentPlaceHolder id="head" runat="server" />
</head>
<body>
        <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
        <h3 class="w3-bar-item">Menu</h3>
        <a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button">Home</a>
        <a asp-controller="Summoners" asp-action="Index" class="w3-bar-item w3-button">Summoners</a>
        <a asp-controller="SummonerRankedLeagueDetails" asp-action="Index" class="w3-bar-item w3-button">Ranked Details</a>
        <a asp-controller="SummonerChampionMasteries" asp-action="Index" class="w3-bar-item w3-button">Champion Masteries</a>
        @if (SignInManager.IsSignedIn(User))
        {<a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Logout</a>}
        </div>

        <!-- Page Content -->
        <div style="margin-left:25%">

            <div class="w3-container w3-teal">
                <h1>Admin Panel</h1>
            </div>


            <div class="w3-container">
                @if (SignInManager.IsSignedIn(User)) {<h2>Hello @User.Identity.Name!</h2> }
                <p>DATA</p>
                <p></p>
            </div>

        </div>
</body>
@RenderBody()
</html>

WebProject/WebProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">WebProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Summoners" asp-action="Index">Summoners</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ChampionRotations" asp-action="Index">Champion Rotation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="SummonerRankedLeagueDetails" asp-action="Index">Ranked Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="SummonerChampionMasteries" asp-action="Index">Summoners</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebProject - <a asp-area="" asp-controller="Home" asp-action="">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>